//! CalNexus 计算域集合。
pub mod arithmetic;
pub mod complex;
pub mod matrix;
pub mod scientific;
pub mod statistics;
pub use arithmetic::ArithmeticDomain;
pub use complex::ComplexDomain;
pub use matrix::MatrixDomain;
pub use scientific::ScientificDomain;
pub use statistics::StatisticsDomain;
